### ISSUE TITLE
streameye dependancys

### ISSUE THREAD

**Issue by coop44483** [ccrisan/streameye#15]
I really hate to bother you but I am having trouble with streameye.  I had it working for a while but all of sudden it stopped working and I do not know what I did to break it! I assumed that I had broken something so I went back and reloaded a fresh image of Stretch, then loaded streameye as per the instructions on this site.

pi@raspberrypi:~/streameye/extras $ raspimjpeg.py -d -w 640 -h 480 -r 15 | streameye -d
bash: raspimjpeg.py: command not found
2018-04-08 11:46:01: INFO : streamEye 0.8
2018-04-08 11:46:01: INFO : hello!
2018-04-08 11:46:01: DEBUG: installing signal handlers
2018-04-08 11:46:01: DEBUG: initializing thread synchronization
2018-04-08 11:46:01: DEBUG: starting server
2018-04-08 11:46:01: INFO : listening on 0.0.0.0:8080
2018-04-08 11:46:01: DEBUG: input: end of stream
2018-04-08 11:46:01: DEBUG: closing server
2018-04-08 11:46:01: DEBUG: waiting for clients to finish
2018-04-08 11:46:01: INFO : bye!

I have tested the Pi camera and it is working correctly.  
What have I forgotten to do?

Thank you 
David Cooper

**Comment by ccrisan** [comment]
What happens if you run just the first part:

    raspimjpeg.py -d -w 640 -h 480 -r 15

?

**Comment by coop44483** [comment]
Thank you for your quick response. 

pi@raspberrypi:~/streameye/extras $ raspimjpeg.py -d -w 640 -h 480 -r 15
bash: raspimjpeg.py: command not found
pi@raspberrypi:~/streameye/extras $ python3 raspimjpeg.py -d -w 640 -h 480 -r 15 
2018-04-10 14:19:15:  INFO: raspimjpeg.py 0.8
2018-04-10 14:19:15:  INFO: hello!
2018-04-10 14:19:15: DEBUG: initializing camera
2018-04-10 14:19:15: DEBUG: using resolution 640x480
2018-04-10 14:19:15: DEBUG: using framerate = 15
2018-04-10 14:19:16: DEBUG: using vflip = false
2018-04-10 14:19:16: DEBUG: using hflip = false
2018-04-10 14:19:16: DEBUG: using rotation = 0
2018-04-10 14:19:16: DEBUG: using brightness = 50
2018-04-10 14:19:16: DEBUG: using contrast = 0
2018-04-10 14:19:16: DEBUG: using saturation = 0
2018-04-10 14:19:16: DEBUG: using sharpness = 0
2018-04-10 14:19:16: DEBUG: using exposure compensation = 0
2018-04-10 14:19:16: DEBUG: using video stabilization = false
2018-04-10 14:19:16: DEBUG: using denoise = false
2018-04-10 14:19:16: DEBUG: using image effect = none
2018-04-10 14:19:16: DEBUG: camera initialized
2018-04-10 14:19:16: DEBUG: starting capture
Traceback (most recent call last):
  File "raspimjpeg.py", line 325, in <module>
    run()
  File "raspimjpeg.py", line 312, in run
    use_video_port=not options.stills, thumbnail=None, quality=options.quality)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1519, in capture_sequence
    encoder.wait()
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 398, in wait
    raise self.exception
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 267, in _callback
    stop = self._callback_write(buf)
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 1054, in _callback_write
    super(PiMultiImageEncoder, self)._callback_write(buf, key)
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 298, in _callback_write
    written = output.write(buf.data)
TypeError: write() argument must be str, not bytes

**Comment by ccrisan** [comment]
Don't run it with python3 as it probably won't work.

**Comment by coop44483** [comment]
If you look at the first line of the previous comment, I did try it without Python3.

pi@raspberrypi:/streameye/extras $ raspimjpeg.py -d -w 640 -h 480 -r 15
bash: raspimjpeg.py: command not found

Then I ran it again with Python3

**Comment by ccrisan** [comment]
Well, where is your `raspimjpeg.py`?

**Comment by ccrisan** [comment]
Use `python2 raspimjpeg.py` or `./raspimjpeg.py`.

**Comment by coop44483** [comment]
Well that seems to have fixed it.  I would have sworn that I tried ./ without success but I must have been wrong!  

Thank you for your help.  As you can probably tell I am a nooby to linux.  Struggling with the conversion from windows!  So much to learn. So little time ( and brain cells).
Again thank you.

**Comment by ccrisan** [comment]
You're welcome.
