### ISSUE TITLE
Getting this after keyboard interruption

### ISSUE THREAD

**Issue by andreluisos** [ccrisan/streameye#16]
Not sure if it's something important, though.

```
2018-11-23 08:45:03: INFO : bye!
Traceback (most recent call last):
  File "/usr/local/bin/raspimjpeg.py", line 325, in <module>
    run()
  File "/usr/local/bin/raspimjpeg.py", line 312, in run
    use_video_port=not options.stills, thumbnail=None, quality=options.quality)
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1519, in capture_sequence
    encoder.wait()
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 393, in wait
    result = self.event.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by ccrisan** [comment]
You can safely ignore that.
